Add openssl support in transport module with some enhancement and bug fix
inclavare-containers/rats-rs pull request #1
Opened 2024-08-06 07:51 UTC by csyJoy

This pr contain three things:
1. Fix bug in `AutoEvidence` which cause incomplete TEE detect.
2. Add tls support using openssl in transport module.
3. Create x509 certificate manually to pass openssl cert pre-verification.
4. Add tls echo client and echo server exmpale.

2024-08-23 08:28 UTC, imlk0 requested changes
A great work. And I've left some comments, pls check them :)

2024-08-23 08:28 UTC, imlk0 commented on rats-rs/src/transport/tls/mod.rs
> +    Ok(())
As mentioned at the OpenSSL [doc](https://docs.openssl.org/1.1.1/man3/OPENSSL_init_ssl/):
```txt
As of version 1.1.0 OpenSSL will automatically allocate all resources that it needs so no explicit initialisation is required.
```

Could you explain that why we need a explicit initialisation for OpenSSL here?

2024-08-23 08:28 UTC, imlk0 commented on rats-rs/src/transport/tls/client.rs
> +        }
It looks that `Client::init()` is called by `TlsClientBuilder::build()` only. What about moving the code of `Client::init()` into `TlsClientBuilder::build()`? In this way, we can remove the `Option<>` from the types of `ctx` and `ssl_session`, thus avoiding the `is_none()` check here.

2024-08-23 08:28 UTC, imlk0 commented on rats-rs/src/transport/tls/server.rs
> +        }
Also check here, as with `struct Client`.

2024-08-23 08:28 UTC, imlk0 commented on rats-rs/src/transport/tls/mod.rs
> +}
Can be replaced with:

```suggestion
lazy_static! {
    static ref OPENSSL_EX_DATA_IDX: i32 =
        unsafe { CRYPTO_get_ex_new_index(4, 0, ptr::null_mut(), None, None, None,) };
}
```

2024-08-23 08:28 UTC, imlk0 commented on rats-rs/src/transport/tls/server.rs
> +                OPENSSL_EX_DATA_IDX.lock().unwrap().get(),
Can be replaced with:

```suggestion
                *OPENSSL_EX_DATA_IDX,
```

2024-08-23 08:28 UTC, imlk0 commented on rats-rs/src/transport/tls/client.rs
> +                OPENSSL_EX_DATA_IDX.lock().unwrap().get(),
Can be replaced with:

```suggestion
                *OPENSSL_EX_DATA_IDX,
```

2024-08-23 08:28 UTC, imlk0 commented on rats-rs/src/transport/tls/mod.rs
> +}
Could you clarify what the purpose of GetFdDumpImpl is?

2024-09-01 04:25 UTC, csyJoy commented
> A great work. And I've left some comments, pls check them :)

Thank you for your suggestion. I have made revisions to the issues raised in last commit :)

2024-09-02 09:11 UTC, merged